# Loads default integrations except Energy (no energy devices configured).
assist_pipeline:
backup:
bluetooth:
config:
conversation:
dhcp:
file:
go2rtc:
history:
homeassistant_alerts:
cloud:
image_upload:
logbook:
media_source:
mobile_app:
my:
ssdp:
stream:
sun:
usage_prediction:
usb:
webhook:
zeroconf:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /hacsfiles/lovelace-mushroom/mushroom.js

# Load dashboards
lovelace:
  mode: storage
  default_dashboard: lovelace-main
  dashboards:
    lovelace-main:
      mode: yaml
      title: Home
      icon: mdi:home
      show_in_sidebar: true
      filename: dashboards/main.yaml
    lovelace-life:
      mode: yaml
      title: Yard
      icon: mdi:sprinkler
      show_in_sidebar: true
      filename: dashboards/life.yaml
    lovelace-security:
      mode: yaml
      title: Security
      icon: mdi:shield-home
      show_in_sidebar: true
      filename: dashboards/security.yaml
    lovelace-wildlife:
      mode: yaml
      title: Wildlife
      icon: mdi:bird
      show_in_sidebar: true
      filename: dashboards/wildlife.yaml
    lovelace-roku:
      mode: yaml
      title: Roku
      icon: mdi:television-play
      show_in_sidebar: true
      filename: dashboards/roku.yaml
    lovelace-recordings:
      mode: yaml
      title: Recordings
      icon: mdi:television-classic
      show_in_sidebar: true
      filename: dashboards/recordings.yaml

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
    - 172.19.0.0/16

logger:
  logs:
    homeassistant.components.unifi: error

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
template: !include templates.yaml
command_line: !include command_line.yaml
