# Enables internal stub_status on port 82 for nginx-prometheus-exporter.
server {
  listen 82;
  server_name localhost;
  location /nginx_status {
    stub_status on;
    access_log off;
    allow 172.16.0.0/12;
    allow 127.0.0.1;
    deny all;
  }
}
